version: "3"

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017 --quiet
      interval: 1s
      timeout: 10s
      start_period: 5s

  firebase:
    build:
      context: emulators
      dockerfile: Dockerfile.firebase
    container_name: firebase
    ports:
      - 4000:4000
      - 4400:4400
      - 9199:9199

  web:
    build:
      context: .
      target: dev
    container_name: web
    command: sh -c "yarn && yarn dev"
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - firebase
    env_file:
      - .env.docker.example

  mongo_seed:
    image: mongo
    links:
      - mongo
    volumes:
      - ./mongo:/mongo
    command:
      /mongo/import.sh
    depends_on:
      mongo:
        condition: service_healthy
