name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      BUILD_TARGET: ci
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp docker-compose.override.yml.ci docker-compose.override.yml
          docker-compose up -d
          docker container ls
      - name: Lint
        run: docker-compose exec -T web yarn lint
